"""sixth migration

Revision ID: 6e2d31ebf70e
Revises: af2bed8bff54
Create Date: 2024-08-03 14:40:10.058912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2d31ebf70e'
down_revision = 'af2bed8bff54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
