"""third migration

Revision ID: d1ac688b192a
Revises: 2efdfcc31cd2
Create Date: 2024-07-31 21:53:51.604795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ac688b192a'
down_revision = '2efdfcc31cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('ratecard',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('ratecard',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('capacity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
